site_name: Pony Tutorial
pages:
- [index.md, Home]
- ["installation/mac-osx.md"]
- ["installation/linux.md"]
- ["installation/windows.md"]
- ["getting-started/what-you-need-to-start.md"]
- ["getting-started/helloworld.md"]
- ["types/classes.md"]
- ["types/primitives.md"]
- ["types/type-alias.md"]
- ["whitespace/sensitivity.md"]
- ["whitespace/semicolons.md"]
- ["whitespace/comments.md"]
- ["whitespace/docstrings.md"]
- ["variables/let-vs-var.md"]
- ["variables/parameters.md"]
- ["variables/fields.md"]
- ["variables/literals.md"]
- ["control-structures/conditionals.md"]
- ["control-structures/operator-precedence.md"]
- ["control-structures/loops.md"]
- ["control-structures/expressions-everywhere.md"]
- ["methods/constructors.md"]
- ["methods/functions.md"]
- ["methods/named-and-default-args.md"]
- ["methods/partial-functions.md"]
- ["actors/behaviours.md"]
- ["actors/capabilities.md"]
- ["actors/recover-and-consume.md"]
- ["actors/arrow-types.md"]
- ["exceptions/try-else-then.md"]
- ["traits-interfaces/traits.md"]
- ["traits-interfaces/interfaces.md"]
- ["packages/package-system.md"]
- ["packages/builtin.md"]
- ["packages/use-statement.md"]
- ["common-sugar/create.md"]
- ["common-sugar/apply.md"]
- ["common-sugar/update.md"]
- ["composition-inheritance/code-sharing.md"]
- ["algebraic-types/union.md"]
- ["algebraic-types/intersection.md"]
- ["algebraic-types/tuple.md"]
- ["generics/polymorphic-types.md"]
- ["generics/polymorphic-methods.md"]
- ["pattern-matching/match.md"]
- ["pattern-matching/as.md"]
- ["object-literals/object-literals.md"]
- ["object-literals/partial-application.md"]
- ["platform/platform.md"]
- ["editor-plugins/plugins.md"]
- ["compiler-clargs/clargs.md"]
- ["patterns/patterns.md"]
- ["garbage-collection/garbage-collection.md"]
- ["c-ffi/calling-c.md"]
- ["c-ffi/linking-c.md"]
- ["c-ffi/c-abi.md"]
- ["examples/examples.md"]
theme: readthedocs
