site_name: Pony Tutorial
theme: readthedocs
pages:
- Getting started:
  - Welcome!: index.md
  - getting-started/what-you-need-to-start.md
  - getting-started/installation.md
  - getting-started/helloworld.md
  - getting-started/how-it-works.md
  - getting-started/whitespace.md
- Types:
  - types/static-vs-dynamic.md
  - types/classes.md
  - types/primitives.md
  - types/actors.md
  - types/traits-and-interfaces.md
  - types/type-aliases.md
  - types/type-expressions.md
- Expressions:
  - expressions/variables.md
  - expressions/infix-ops.md
  - expressions/control-structures.md
  - expressions/methods.md
  - expressions/exceptions.md
  - expressions/sugar.md
  - expressions/object-literals.md
  - expressions/partial-application.md
- Capabilities:
  - capabilities/object-capabilities.md
  - capabilities/reference-capabilities.md
  - capabilities/guarantees.md
  - capabilities/aliasing.md
  - capabilities/consume-and-destructive-read.md
  - capabilities/recovering-capabilities.md
  - capabilities/combining-capabilities.md
  - capabilities/passing-and-sharing.md
  - capabilities/capability-subtyping.md
  - capabilities/arrow-types.md
  - capabilities/trust-boundary.md
- Generics:
  - generics/polymorphic-types.md
  - generics/polymorphic-methods.md
- packages/package-system.md
- composition-inheritance/code-sharing.md
- Pattern Matching:
  - pattern-matching/match.md
  - pattern-matching/as.md
- platform/platform.md
- Editor support: editor-plugins/plugins.md
- Compiler args: compiler-clargs/clargs.md
- patterns/patterns.md
- C FFI:
  - Calling C: c-ffi/calling-c.md
  - Linking to C Libraries: c-ffi/linking-c.md
  - c-ffi/c-abi.md
- The Runtime:
  - runtime/memory-allocation.md
  - runtime/garbage-collection.md
- examples/examples.md
