site_name: Pony Tutorial
pages:
- [index.md, Home]
- ["installation/mac-osx.md", "Installation", "Mac OSX"]
- ["installation/linux.md", "Installation", "Linux"]
- ["installation/windows.md", "Installation", "Windows"]
- ["getting-started/what-you-need-to-start.md"]
- ["getting-started/helloworld.md"]
- ["getting-started/how-it-works.md"]
- ["getting-started/whitespace.md"]
- ["types/static-vs-dynamic.md"]
- ["types/classes.md"]
- ["types/primitives.md"]
- ["types/actors.md"]
- ["types/traits-and-interfaces.md"]
- ["types/type-aliases.md"]
- ["variables/variables.md"]
- ["control-structures/control-structures.md"]
- ["methods/methods.md"]
- ["actors/behaviours.md"]
- ["actors/capabilities.md"]
- ["actors/recover-and-consume.md", "Actors", "recover and consume"]
- ["actors/arrow-types.md"]
- ["exceptions/exceptions.md", "Exceptions", "Exceptions"]
- ["packages/package-system.md"]
- ["packages/builtin.md"]
- ["packages/use-statement.md", "Packages", "Using a package"]
- ["common-sugar/common-sugar.md", "Common sugar", "Sugar"]
- ["composition-inheritance/code-sharing.md", "Composition vs. inheritance"]
- ["algebraic-types/union.md"]
- ["algebraic-types/intersection.md"]
- ["algebraic-types/tuple.md"]
- ["generics/polymorphic-types.md"]
- ["generics/polymorphic-methods.md"]
- ["pattern-matching/match.md", "Pattern matching", "match-expression"]
- ["pattern-matching/as.md", "Pattern matching", "as-expression"]
- ["object-literals/object-literals.md"]
- ["object-literals/partial-application.md"]
- ["platform/platform.md"]
- ["editor-plugins/plugins.md", "Editor support", "Plugins"]
- ["compiler-clargs/clargs.md", "Compiler options", "Overview"]
- ["patterns/patterns.md"]
- ["garbage-collection/garbage-collection.md"]
- ["c-ffi/calling-c.md", "C-FFI", "Calling C programs"]
- ["c-ffi/linking-c.md", "C-FFI", "Linking to C libraries"]
- ["c-ffi/c-abi.md", "C-FFI", "Exposing a C-ABI"]
- ["examples/examples.md"]
theme: readthedocs
