site_name: Pony Tutorial
pages:
- [index.md, Home]
- ["installation/mac-osx.md", "Installation", "Mac OSX"]
- ["installation/linux.md", "Installation", "Linux"]
- ["installation/windows.md", "Installation", "Windows"]
- ["getting-started/what-you-need-to-start.md"]
- ["getting-started/helloworld.md"]
- ["getting-started/how-it-works.md"]
- ["getting-started/whitespace.md"]
- ["types/static-vs-dynamic.md"]
- ["types/classes.md"]
- ["types/primitives.md"]
- ["types/actors.md"]
- ["types/traits-and-interfaces.md"]
- ["types/type-aliases.md"]
- ["types/type-expressions.md"]
- ["capabilities/type-qualifiers.md"]
- ["capabilities/guarantees.md"]
- ["capabilities/aliasing.md"]
- ["capabilities/combining-capabilities.md"]
- ["capabilities/passing-and-sharing.md"]
- ["expressions/variables.md"]
- ["expressions/infix-ops.md"]
- ["expressions/control-structures.md"]
- ["expressions/methods.md"]
- ["expressions/exceptions.md"]
- ["expressions/sugar.md"]
- ["expressions/object-literals.md"]
- ["expressions/partial-application.md"]
- ["actors/behaviours.md"]
- ["actors/capabilities.md"]
- ["actors/recover-and-consume.md", "Actors", "recover and consume"]
- ["actors/arrow-types.md"]
- ["packages/package-system.md"]
- ["packages/builtin.md"]
- ["packages/use-statement.md", "Packages", "Using a package"]
- ["composition-inheritance/code-sharing.md", "Composition vs. inheritance"]
- ["generics/polymorphic-types.md"]
- ["generics/polymorphic-methods.md"]
- ["pattern-matching/match.md", "Pattern matching", "match-expression"]
- ["pattern-matching/as.md", "Pattern matching", "as-expression"]
- ["platform/platform.md"]
- ["editor-plugins/plugins.md", "Editor support", "Plugins"]
- ["compiler-clargs/clargs.md", "Compiler options", "Overview"]
- ["patterns/patterns.md"]
- ["garbage-collection/garbage-collection.md"]
- ["c-ffi/calling-c.md", "C-FFI", "Calling C programs"]
- ["c-ffi/linking-c.md", "C-FFI", "Linking to C libraries"]
- ["c-ffi/c-abi.md", "C-FFI", "Exposing a C-ABI"]
- ["examples/examples.md"]
theme: readthedocs
